[build]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[crons]]
name = "youtube-download"
schedule = "0 */2 * * *"
command = "python youtube_downloader.py"